### ISSUE TITLE
[Tarea 1 P1] - Llaves equivalentes

### ISSUE THREAD

**Issue by VicenteVicente** [UC-IIC3253/2022#10]
Hola quería saber si al revisar considerarán que existen llaves equivalentes. Por ejemplo, supongamos que se encriptó usando la llave:
k=ABABAB
y yo entrego de output:
k'=AB
En la teoría, mi llave k' es capaz de decriptar los mismos mensajes que la llave k. Eso está bien?

Saludos

**Comment by mugartec** [comment]
Hola @VicenteVicente, disculpa la demora. En ese caso ambas llaves estarían correctas. De hecho lo que buscamos es medir qué tan buena es una llave en base a la "distribución" del texto que resulta decriptar con ella, y para esas dos llaves dicha distribución sería igualmente buena.

**Comment by VicenteVicente** [comment]
Gracias!
