### ISSUE TITLE
[Tarea 1 - P3] Inputs de las funciones

### ISSUE THREAD

**Issue by AndresGonzalez5** [UC-IIC3253/2022#11]
Hola! Estaba haciendo las funciones de ``get_proof_for`` y ``verify``, y no estaba seguro respecto al 'item' que mencionan entra a cada función. Me tinca que en la función ``verify`` entra el string sin ser hasheado, mientras que en ``get_proof_for`` entra el hash del string. La verdad estoy adivinando y cambia un poco la cosa con los inputs así que preguntaba para asegurarme :).

**Comment by mugartec** [comment]
Hola @AndresGonzalez5, en ambos casos el item es el texto plano, no la función de hash. La idea es siempre verificar que el item mismo es parte del conjunto. Basta con el item porque en base a él puedo obtener su función de hash. Me cuentas si se entiende.
