### ISSUE TITLE
Pregunta 3: Retorno de función get_proof_for

### ISSUE THREAD

**Issue by jorge-schenke** [UC-IIC3253/2022#12]
Hola, tenía la siguiente duda en cuanto a lo que tiene que retornar la función get_proof_for de la clase MerkleTree:

En el enunciado dice: "None if the item is not part of the leafs of the tree. A list with the necessary info to prove that the item is part of the leafs of the tree".
¿Es estrictamente necesario que sea una lista lo retornado? se me hace un poco difícil a través de una lista dejar 100% claro que es parte del árbol, es posible que en vez de retornar una lista hagamos una serie de prints que muestren los ancestros del nodo encontrado y diga que no está en el árbol en caso contrario?.

**Comment by mugartec** [comment]
Hola @jorge-schenke. No hay problema con que el programa imprima lo necesario para que una persona se convenza de que el elemento está efectivamente en las hojas del árbol, pero la función **tiene que retornar** lo que se especifica en el enunciado, ya que es lo necesario para hacer la verificación de forma automática.
