### ISSUE TITLE
Tarea 1 P1 - largo máx de llaves

### ISSUE THREAD

**Issue by hrhartmann** [UC-IIC3253/2022#13]
Hola ! Podemos asumir un máximo de largo de llave ? No se si estoy haciendo algo mal, pero mi algoritmo está llegando a los 10s con llaves de largo 100 y además la precisión baja bastante.

**Comment by mugartec** [comment]
Hola @hrhartmann. En principio no, el algoritmo tiene que ser general y funcionar para cualquier largo. Considera eso sí que el único límite de tiempo que vamos a exigir es el que sale en el enunciado. Si se demora mucho para llaves muy largas no es problema.

**Comment by hrhartmann** [comment]
Perfect !

**Comment by DiegoEmilio01** [comment]
@mugartec hola profe, a qué se refiere con llaves muy largas? Mi algoritmo es muy eficiente para el largo del texto cifrado pero muy costoso para el largo de la llave. En particular cuando |key|>= 5 se vuelve pesado, el tema es que para un texto de 1000 carácteres (como sugiere el enunciado) el máximo largo de una llave es 20 (por la restricción de que es a lo más 50 veces menor).
