### ISSUE TITLE
[Materia] Definición función despreciable

### ISSUE THREAD

**Issue by kylevon** [UC-IIC3253/2022#14]
En el ppt se define una función despreciable de esta manera:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/46159219/164067118-e996a9b6-b916-4a78-832a-f57ba319745e.png">
Luego, un polinomio cualquiera puede ser p(n) = -n. Y en este caso, ya que f : ℕ → ℕ , para todo f y todo n, 0 f(n) < 1/-n. 

Por lo tanto, creo que en la definición hay que escribir que p es  p: ℕ → ℕ .

**Comment by marceloarenassaavedra** [comment]
La condición que mencionas estaba implícita en la definición, pero tienes razón que es mejor que esta condición aparezca de manera explícita. Está cambiada la presentación incluyendo la condición `p : N -> N`. Gracias!

**Comment by kylevon** [comment]
Gracias!
