### ISSUE TITLE
T1 - Uso de librerías (NumPy y Math)

### ISSUE THREAD

**Issue by fguinez** [UC-IIC3253/2022#15]
¿Podemos usar las librerías [NumPy](https://numpy.org/doc/stable/) y [math](https://docs.python.org/3/library/math.html)?

Claramente no son imprescindibles, pero ayudarían para simplificar operaciones puntuales.

Por el lado de NumPy, pienso aprovechar las operaciones sobre arrays.

Por el lado de math, pienso utilizar funciones como ceil, floor o fmod.

Saludos!

**Comment by mugartec** [comment]
Hola @fguinez qué operaciones simplificarían en particular?

**Comment by fguinez** [comment]
La verdad ya no estoy tan seguro de necesitar numpy😅. Pero en el caso de math, hasta ahora estoy usando math.ceil para quedarme con el techo de una división.

Intentaré dar un ejemplo sin spoilear nada:
Tengo una división de `m/n` y quiero el siguiente comportamiento:
- Si `m/n = 10/2 = 5.0`, entonces quiero 5
- Si `m/n = 11/2 = 5.5`, entonces quiero 6

Por ello, si hago `math.ceil(m/n)` obtengo el comportamiento deseado.

Realmente es algo que se puede implementar fácilmente, pero como es parte de la librería estándar de Python veo lógico usarlo.

**Comment by fguinez** [comment]
Finalmente implementé mis soluciones sin utilizar ninguna de las 2 librerías, así que cerraré esta issue
