### ISSUE TITLE
[T1 P2] Duda sobre como abordar la pregunta

### ISSUE THREAD

**Issue by ibaeza1** [UC-IIC3253/2022#17]
Hola!
Estoy teniendo problemas sobre como abordar la P2. No entiendo exactamente cual es la probabilidad que hay que calcular ni como funciona el esquema criptográfico. En la ayudantía 2 hacen algo parecido pero ahi explican cual es el 'juego', es decir explican que hace el adversario y despues dicen que es OTP por lo que se puede deducir que hay que calcular el xor entre mi y ci.
En la pregunta de la tarea no nos dicen mucho sobre como funciona el sistema por lo que no entiendo muy bien como empezar a responder la pregunta.
No se si es posible guiarme un poco sobre que es lo que se busca o explicar un poco mas la pregunta :). Es posible abordarla de manera parecida a la ayudantía? O lo estoy entendiendo mal?
Gracias!

**Comment by marceloarenassaavedra** [comment]
Hola!

Del esquema criptográfico `(Gen, Enc, Dec)` sabes solo lo que se menciona en el enunciado: 

- Tanto el espacio de llaves, como de mensajes y textos cifrados es `{0,1}^n`
- `Gen(0x) = 0` para todo `x` en `{0,1}^(n-1)`
- `Gen(1x) = 1/2^(n-1)` para todo `x` en `{0,1}^(n-1)`

Lo que tienes que demostrar es que un adversario puede en una ronda distinguir con una probabilidad mayor o igual a `3/4` si el verificador está usando este esquema criptográfico o una permutación sacada al azar (como fue definido en clases clases para la noción de pseudo-random permutation). Algo importarte  a considerar aquí es que el adversario tiene poder computacional ilimitado, por lo que puede ejecutar un algoritmo de tiempo exponencial. 

Saludos!
