### ISSUE TITLE
[Tarea 1 P1] Restricciones al largo de la llave

### ISSUE THREAD

**Issue by fguinez** [UC-IIC3253/2022#18]
¿Podemos asumir que el largo de la llave divide exactamente al largo del mensaje? ¿O debemos considerar casos en que, en la última fracción, la llave se utiliza parcialmente?

Por dar un ejemplo, si consideramos el string `ABCDEFGHIJ` (de largo 10), ¿la llave puede ser `XYZ` (largo 3)?
Me imagino que de ser el caso el cifrado se calcularía con los siguientes conjuntos mensaje-llave:
`ABC` `DEF` `GHI` `J`
`XYZ` `XYZ` `XYZ` `X`

**Comment by mugartec** [comment]
Hola @fguinez. Deben considerar el algoritmo tal como está descrito en el enunciado, que es exactamente como lo describes al final. No se puede asumir que el largo de la llave divide exactamente al largo del mensaje.

**Comment by fguinez** [comment]
Gracias!
