### ISSUE TITLE
T1 -  Librería numba

### ISSUE THREAD

**Issue by FarDust** [UC-IIC3253/2022#19]
Hola me gustaría saber si es posible usar `numpy` y  `numba` como librerías.

numpy en especial porque es mucho mas eficiente en el manejo de arrays y numba para pre-compilar las funciones que realicen calculos.

https://numba.pydata.org/

**Comment by mugartec** [comment]
Hola @FarDust en esta primera tarea no, o al menos no por temas de eficiencia. La restricción de tiempo que se pide debería ser lo suficientemente holgada para que se preocupen de la limpieza del código más que de la eficiencia.
