### ISSUE TITLE
[Tarea 1 P3] verify signature

### ISSUE THREAD

**Issue by ptflores1** [UC-IIC3253/2022#2]
Hola!
Es posible que en la signature de verify que se entrega en el enunciado falte incluir un argumento para la función de hash?
Según entiendo para revisar que un elemento es parte del árbol hay que calcular los hashes de las concatenaciones de algunos strings, para eso necesitaríamos tener acceso a la función de hash.

Saludos!

**Comment by mugartec** [comment]
Hola @ptflores1. Efectivamente, good catch. Alguien se la juega con el PR?

**Comment by ptflores1** [comment]
@mugartec creado!

**Comment by mugartec** [comment]
Mergeado, gracias!!
