### ISSUE TITLE
[T1 P1] Solucion de problema en clases

### ISSUE THREAD

**Issue by Jaluco** [UC-IIC3253/2022#20]
Sería posible que nos facilitaran el codigo que se uso en clases? No se si esta disponible ya en alguna parte pero no lo he encontrado. En las diapositivas al menos no se entra mucho en detalle sobre lo que se hizo

**Comment by mugartec** [comment]
Hola @Jaluco. No, el código de la clase no está publicado a propósito. Como lo programamos en vivo el código quedó feo y consideramos mejor que lo escriban de cero.

**Comment by Jaluco** [comment]
Y podrían darnos alguna aproximacion? Fui a la clase pero no recuerdo bien la relacion entre la distribucion de probabilidades de las letras y el algoritmo para decriptar. Incluso un pseudocodigo sería muy útil para todos creo yo

**Comment by marceloarenassaavedra** [comment]
Hola!

Si aún estás pegado en esta pregunta, una fuente de inspiración para una solución al problema está el capítulo 1 del texto guía del curso:

- Jonathan Katz y Yehuda Lindell. Introduction to Modern Cryptography. Chapman and Hall/CRC, tercera edición, 2020.

Saludos!

**Comment by Jaluco** [comment]
Me puse a revisar el libro y el problema con frecuencias que se ve es un paso estatico de un alfabeto a otro, no OTP ni mucho menos con la key como la misma palabra dos veces, en que parte esta lo de a clase?
