### ISSUE TITLE
[T1 P1] Llaves Equivalentes

### ISSUE THREAD

**Issue by BFFV** [UC-IIC3253/2022#21]
Hola!

Probando me di cuenta de que pueden existir múltiples llaves que sirvan para desencriptar el mensaje cifrado, por ejemplo:
Si la llave es ABC, también es equivalente a usar ABCABC, ABCABCABC, y en realidad el patrón (ABC)+.

En estos casos, ¿da lo mismo cual de esas llaves nuestra función entregue?¿o debemos asumir otra cosa?

**Comment by marceloarenassaavedra** [comment]
Sí, cualquiera de las llaves que entregues en este caso estaría correcta.

Esto fue discutido en el issue #10.

Saludos!

**Comment by BFFV** [comment]
Gracias!
