### ISSUE TITLE
[T1 P3] Merkle Tree con |S| = 1

### ISSUE THREAD

**Issue by BFFV** [UC-IIC3253/2022#24]
Hola!

Tenía la duda de como debería verse el caso borde en el que el árbol sólo representa 1 string **s**:

**A)** Una raíz h(h(**s**)||h(**s**)), con ambos hijos h(**s**)
**B)** El único nodo es la raíz y es igual a h(**s**)

Imagino que es el caso **A**, pero pregunto para estar seguro.

**Comment by mugartec** [comment]
Hola @BFFV, la verdad es que ambas opciones serían válidas y funcionarían bien. Personalmente me inclinaría por la B, pero cualquiera que implementen va a funcionar bien.

Para asegurarnos de no generar confusión, pueden suponer que el árbol siempre tendrá al menos dos hojas.
