### ISSUE TITLE
[T1] Test Cases

### ISSUE THREAD

**Issue by Brocoleta** [UC-IIC3253/2022#26]
Hola, subiran test cases para probar nuestras respuestas / adaptarlas al formato del input?

**Comment by mugartec** [comment]
Hola @Brocoleta Haré lo posible por subir test cases mañana para que los puedan probar. Los subiré como issues, para que le den al :eye: Watch.

**Comment by mugartec** [comment]
Perdón la demora, anoche subí ejemplos para la P3 [aquí](https://github.com/UC-IIC3253/2022/issues/34). Voy a hacer lo posible por subir ejemplos de la P1 en la tarde pero no estoy seguro de que alcance...
