### ISSUE TITLE
[T1 P1] Manejo de mayúsculas y minusculas

### ISSUE THREAD

**Issue by Zetaku1** [UC-IIC3253/2022#27]
Hola!

En la pregunta 1 esperamos que el diccionario de frecuencias contenga letras mayúsculas y minúsculas o debemos nosotros adaptar el texto para poder contabilizar bien las frecuencias?

**Comment by mugartec** [comment]
Hola @Zetaku1. Tu programa debiese tratar una letra mayúscula y una letra minúscula simplemente como dos caracteres distintos no relacionados.

**Comment by Zetaku1** [comment]
ok, gracias!
