### ISSUE TITLE
[Tarea 1 P1] orden de los elementos en el abecedario

### ISSUE THREAD

**Issue by jeschuwirth** [UC-IIC3253/2022#3]
Considerando que para la P1 nos dan un abecedario cualquiera, y que la única guía a este abecedario es el parámetro frequencies el cuál es un diccionario. ¿Cómo podemos saber el valor numérico de cada carácter en el abecedario? Dando un ejemplo, si tengo:

freq = {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
m = 'A'
k = 'B'
c = Enc(k, m)

Por lo que entiendo es imposible predecir el valor de c. Sabemos que el abecedario solo tiene 4 caracteres, por lo que sus valores van a ser 0,1,2,3. Pero no hay forma de saber si A es 0 y B es 1 u otra combinación ya que la tabla frequencies es un diccionario que por definición no tiene sus elementos ordenados.

**Comment by mugartec** [comment]
Hola @jeschuwirth. Muy buen punto, faltó especificarlo. Lo que podríamos hacer es suponer que la enumeración es consistente con la forma en que Python ordena los strings. Es decir, suponer que el alfabeto es `sorted(frequencies.keys())`. Suena bien? Le ves alguna inconsistencia?

Siguiendo tu ejeplo:
```python
>>> freq = {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
>>> alph = sorted(freq.keys())
>>> print(alph)
['A', 'B', 'C', 'D']
```
Con esto la `A` sería el `0` y la `B` el `1`, y `Enc('B', 'A')='B'`.

**Comment by jeschuwirth** [comment]
Me parece perfecto.

Gracias!
