### ISSUE TITLE
[T1 P3] Restricción almacenar hash y valores

### ISSUE THREAD

**Issue by DiegoEmilio01** [UC-IIC3253/2022#30]
Hola, hay alguna restricción con guardar la lista de valores y el hash en la clase MerkleTree?

**Comment by DiegoEmilio01** [comment]
También, alguna restricción sobre cómo construir el árbol o mientras los retornos estén correctos estaría bueno?

**Comment by bmurtagh01** [comment]
Yo le pregunté esto al profesor hoy en la clase y me dijo que no importaba guardar los valores, que la implementacióon del árbol era nuestra decisión.

**Comment by DiegoEmilio01** [comment]
bacan gracias!
