### ISSUE TITLE
[T1 P3] Item en arbol de Merkle

### ISSUE THREAD

**Issue by JJJGGGG** [UC-IIC3253/2022#32]
A qué se refiere con un item en el arbol de merkle en la función ```verify```? Deben ser valores de los nodos hoja del árbol (ej. `"a"` ) o pueden ser valores en lugares arbitrarios del árbol (ej. `h("a")`, `h(h("a")||h("b"))`?

**Comment by BFFV** [comment]
Creo que la issue #11 responde tu duda (se pregunta siempre por las hojas, aunque las hojas se espera que sean los hash de los strings y no los strings mismos).
