### ISSUE TITLE
[T1 - P3] Orden lista proof

### ISSUE THREAD

**Issue by andresplass** [UC-IIC3253/2022#33]
Hola, por saber podemos asumir que la lista proof que se entrega a verify estará ordenada? (por ordenada me refiero a que de izquierda a derecha en la lista proof, será de abajo hacia arriba en los nodos del árbol) o esta puede venir desordenada?

Como pregunta similar, verify requeriría que esté ordenada para retornar True o puede venir en desorden e igual ser una prueba correcta?

gracias :)

**Comment by mugartec** [comment]
Hola @andresplass. Efectivamente siempre supondremos que la lista viene ordenada de abajo hacia arriba. Intuitivamente, la lista debe contener el hermano del elemento, luego el hermano de su padre, luego el hermano de su abuelo, y así hasta llegar un nivel más abajo de la raíz (la raíz no es parte de la lista). Ahora voy a publicar un issue con ejemplos para esa pregunta.
