### ISSUE TITLE
Error al decriptar notas

### ISSUE THREAD

**Issue by gicrot** [UC-IIC3253/2022#40]
Hola,

Encontré mi archivo de nota correctamente con el sha256 (y le cambié el nombre a `notas.zip.enc`) pero no sé bien como decriptarlo. He intentado con OpenSSL con el siguiente código:

`openssl enc -aes-256-cbc -d -md sha256 -a -in notas.zip.enc -out notas.zip`

Pero al ingresar mi contraseña retorna `bad decrypt`

**Comment by gicrot** [comment]
Update:

Todos mis errores consistían en que mi PC usaba LibreSSL en vez de OpenSSL, lo vi corriendo en la terminal `openssl version`, ya que me decía:

```
ζ openssl version                                                              
LibreSSL 2.8.3
```

Lo solucioné escribiendo `export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"` y verificando que uso OpenSSL con el comando de arriba y ahí podía usar bien otro comando para decriptar

**Comment by marceloarenassaavedra** [comment]
Hola!

Efectivamente tienes que usar `openssl`. Enviamos un correo con las indicaciones para que cada uno pueda desencriptar la corrección de su tarea, por favor usa la instrucción que enviamos ahí que además indica que se debe usar `pbkdf2`.

Saludos!
