### ISSUE TITLE
[T1P1] - "CommitT1:  nan"

### ISSUE THREAD

**Issue by VicenteVicente** [UC-IIC3253/2022#41]
Hola!, estuve conversando con algunos compañeros y varios tenemos este feedback en nuestra pregunta. Pareciera que este mensaje hace referencia a que hubo algún error con el commit de nuestra entrega y no pudo ser revisado. Agradecería saber bien qué significa o qué ocurrió a los que tenemos este feedback.

Saludos y gracias :)

**Comment by marceloarenassaavedra** [comment]
Enviamos un correo con las instrucciones para la recorrección de la tarea 1. Por favor consideren que el plazo para entregar la recorrección es el lunes 6 de junio (una semana a partir de mañana).

Saludos!
