### ISSUE TITLE
[T2P1] - Orden de parámetros en encrypt

### ISSUE THREAD

**Issue by VicenteVicente** [UC-IIC3253/2022#43]
Hola, para la función `encrypt: (bytearray, bytearray) -> bytearray` usada en `davies_meyer`, ¿Cuál de los argumentos corresponde a la llave (y cuál al mensaje)?

**Comment by marceloarenassaavedra** [comment]
En la tarea seguimos la convención usada en el curso para la función `encrypt`, el primer parámetro es la llave y el segundo es el mensaje. 

Saludos!

**Comment by VicenteVicente** [comment]
Gracias 😄
