### ISSUE TITLE
[T2P2] - Caso borde en la encriptación

### ISSUE THREAD

**Issue by VicenteVicente** [UC-IIC3253/2022#45]
Hola!

Si $N$ se representa en menos que $8$ bits, entonces ningún $n\in\mathbb{Z}^+$ satisface que $8\cdot n < bits(N)$. ¿Asumimos que este caso jamás ocurrirá?

**Comment by marceloarenassaavedra** [comment]
Sí, puedes suponer que este caso no va a ocurrir.

Saludos!

**Comment by VicenteVicente** [comment]
Gracias!

**Comment by jtcaraball** [comment]
Hola! @mugartec Me surge una duda dada esta issue. El enunciado pide que $n$ sea un múltiplo de 8 por lo que $n \geq 8$ y por ende $bits(N)$ debería ser siempre mayor a 64 para que se cumpla que $n \cdot 8 < bits(N)$ o no?
