### ISSUE TITLE
[T2P2] Formato encrypt

### ISSUE THREAD

**Issue by IchottMano** [UC-IIC3253/2022#49]
Hola!

No me queda del todo claro cual debería ser el formato del mensaje al ser encriptado por bloques,

¿Es necesario enviar el tamaño de cada bloque en el mensaje, además de la cantidad de bloques o algo así?

Por el momento, lo que estoy haciendo es poner en los primeros 4 bytes del texto encriptado la cantidad de bloques y antes de cada bloque pongo el largo en bytes de cada bloque, y parece funcionarme bien, pero me gustaría cersiorarme.

Quedo atento,

**Comment by mugartec** [comment]
Hola @IchottMano.

El tamaño del bloque se obtiene de la llave, no del mensaje encriptado. Cuando trato de decriptar con una llave pública `(e, N)` entonces el tamaño de bloque (denominado `n` en cantidad de bytes)  será el mayor número tal que `8*n` es menor que el número de bits de `N`. Por ejemplo si para escribir `N` necesito 2056 bits entonces `n` será 256.  Esto está especificado al final del enunciado en "Detalles de implementación". Avísame por favor si entendí bien la pregunta y con esto queda claro o si hay algo que falta.

**Comment by IchottMano** [comment]
Hola @mugartec !

Claro, mi problema era que el numero de bytes de cada bloque encriptado podía ser variable, entonces necesitaba de valores para definir bien los largos. 
Si entendí bien entonces, debería dejar cada bloque encriptado del mismo tamaño y de esta forma leerlo, no?

Muchas gracias,
