### ISSUE TITLE
[Tarea 1 P2] Valor de n

### ISSUE THREAD

**Issue by mc-cari** [UC-IIC3253/2022#5]
Hola, en la pregunta 2, es necesario el valor de n? Para calcular el valor de las probabilidades.

**Comment by marceloarenassaavedra** [comment]
Hola!

Sí, es necesario el valor de `n` en esta pregunta (por ejemplo, es importante que los espacios de mensajes, textos cifrados y llaves sean igual a `{0,1}^n`).

Saludos!

**Comment by mc-cari** [comment]
Entonces n tiene un valor? Por ejemplo n = 10

**Comment by marceloarenassaavedra** [comment]
La probabilidad que tienes que calcular depende de `n` como en los ejemplos que vimos en clases. En particular, `n` es un número natural arbitrario.

**Comment by mc-cari** [comment]
Vale gracias
