### ISSUE TITLE
[T2P2] Formato al encriptar bloques

### ISSUE THREAD

**Issue by mc-cari** [UC-IIC3253/2022#51]
Hola, en la función encrypt de RSASender, se calcula el tamaño de los bloques a encriptar "n", pero al encriptar cada bloque, queda un numero que puede no caber en el bloque de tamaño n, por ejemplo tengo un numero N, y su cantidad de bits es 18, entonces n = 2 y para calcular la encriptacion de ese bloque en RSA me queda un numero modulo N, entonces puede ser que el resultado sea N-1, y este numero necesita 4 bytes para ser representado en bytearray, lo cual es mayor al tamaño de bloque de 2 bytes, hay algo que entendí mal, o es necesario hacer que todos los bloques encriptados sean del mismo tamaño?

**Comment by mugartec** [comment]
Hola @mc-cari. Tienes toda la razón. Para encriptar un bloque de `n` bytes (de acuerdo al `n` definido en la tarea) necesitamos usar `n+1` bytes. Lo vamos a corregir durante el fin de semana y enviaremos un correo con la rectificación y ejemplos para que esté claro. Muchas gracias por notarlo. Saludos!

**Comment by mc-cari** [comment]
Vale gracias!
