### ISSUE TITLE
[T2P2] Bloques encrypt

### ISSUE THREAD

**Issue by Ignaciomendezp** [UC-IIC3253/2022#52]
Hola! Tengo un par de dudas con respecto a la encriptacion.
1. No me queda claro si al momento de hacer la encriptación, debemos primero separar el mensaje y luego encriptar cada bloque por separado, o si tenemos que encriptar el mensaje entero, y luego separarlo en bloques.
2. Tampoco me queda muy claro porque los `n` bytes por bloque tienen que ser menor estricto (**en vez de menor o igual**) que el numero de bits que ocupa `N`. Es decir, si mi `N` ocupa 16 bits, ¿Porqué no puedo puedo ocupar `n` como 2? Segun el enunciado, tendria que  seleccionar `n` como 1, y asi el ultimo bloque del mensaje seria completamente vacio.
3. Tampoco me queda claro la idea de separar el mensaje en bloques, en vez de trabajar con el mensaje directamente.

Muchas gracias!

**Comment by mugartec** [comment]
Hola @Ignaciomendezp.

1. Tienes que pasar el mensaje a bytearray y luego ese bytearray dividirlo en bloques de `n` bytes. Por ejemplo si `n` vale 10 y tu bytearray tiene 25 bytes, entonces vas a encriptar 3 bloques.
2. Si `N` ocupa 16 bits entonces el valor numérico de `N` podría ser, por ejemplo `1010101010101010`. Si tomamos `n` igual a 2, el bloque podría ser por ejemplo `1110101010101010`, y con eso lo que vas a encriptar sería mayor a `n`. Por eso en ese caso usaríamos bloques de 1 byte. Ojo eso sí con [esto](https://github.com/UC-IIC3253/2022/issues/51), ese mismo bloque al encriptarlo va a usar 2 bytes.
3. Creo que se responde con las dos anteriores, pero si faltó algo me cuentas porfa.
