### ISSUE TITLE
[T2P2] - Tiempo de generación de P y Q

### ISSUE THREAD

**Issue by VicenteVicente** [UC-IIC3253/2022#53]
Hola!,

Se supone que recibimos un parámetro llamado ```bit_len``` que define el largo mínimo que debe tener N (en bits). Esto abre la posibilidad a que N sea de tan largo como queramos (siemprey cuando sea mayor que ````bit_len```) y podría significar un impacto en el tiempo de generación de los primos variable entre cada implementación. ¿Tenemos alguna cota superior en el tiempo de generación de P y Q?

Saludos

**Comment by marceloarenassaavedra** [comment]
Hola!

El valor más grande que vamos usar para `bit_len` es 2048 (aproximadamente 617 dígitos decimales), para lo cual se necesita generar primos de al menos 1024 bits (aproximadamente 309 dígitos decimales). Generar un número primo de 1024 bits no debería tomar más de 5 segundos, usa esto como cota superior.

Saludos!

**Comment by VicenteVicente** [comment]
Genial, muchas gracias!

**Comment by DiegoEmilio01** [comment]
@marceloarenassaavedra no hay ninguna restricción respecto a P y Q? N es tan débil cómo el primo más chico y hay que tratar que sean del mismo largo, pero podría elegir un P mucho más pequeño que Q por eficiencia o algo por el estilo.
