### ISSUE TITLE
[T2P2] Caso de prueba para la pregunta 2

### ISSUE THREAD

**Issue by mugartec** [UC-IIC3253/2022#54]
En este issue les dejamos un ejemplo para que puedan probar su clase `RSASender`. Si tienen esta clase funcionando bien, pueden probar que su clase `RSAReceiver` también está buena simplemente verificando que interactúe bien con `RSASender`.

Supongamos que queremos instanciar un `RSASender` con la siguiente llave pública, que es un `bytearray` en el formato pedido en la tarea y expresada en base64.
```
AAAAQQGHaihgiufnjzyLXufDjUCGuaHrsUL+hCF/pMFHPoh+ZVi/2bMFh6oelzElVklsJ9mglyQjJIKAb1JB9mvtaEkLAAAAQQHIuF+wIJw6uzq8uXpW/QmsNjtBJ8HCJJcu2h7sDX18nc2qWYDWTfMiXPmPRvhkkz4A0oXTAMDP9xsxUIjYQNsx
```

Si con dicha instancia encriptamos el siguiente mensaje

> Being open source means anyone can independently review the code. If it was closed source, nobody could verify the security. I think it’s essential for a program of this nature to be open source.

entonces obtenemos un `bytearray`, que expresado en base 64 es
```
ALwPm7JXWbqGeIflV8PYgprs6mSgCH2Ydy0rgvFolzY0mczKItlPSHueL54uvDJXIz9pXoHZGAOPWVYYbcwRh3EBl8pi3MraUC2BBFUviMPFwNMwza/QMd5DNG9tH8doHlLRRt+15wLrsIE+m5T8fuM4HHixSNcEoOdN8T++q0PkzQDXL+UgbusiD3J+QPO59aqAB5HFcZ7P5U3fhFS8Qm1vLG8vlIulCby0jGLgjTtLUhFD/QhAof0y4F20gxedQDHwAOIrz6PEoBWnHmwLU0QNN0Rs542RvJ8BeEGhBDS5ZvD0/0Ix3ZqKT6HtP4ugfPD75/5LYGioJBwrg2DXbQucFj8=
```

Veámoslo ahora en código:
``` python
from base64 import b64encode, b64decode
public_key = b64decode('AAAAQQGHaihgiufnjzyLXufDjUCGuaHrsUL+hCF/pMFHPoh+ZVi/2bMFh6oelzElVklsJ9mglyQjJIKAb1JB9mvtaEkLAAAAQQHIuF+wIJw6uzq8uXpW/QmsNjtBJ8HCJJcu2h7sDX18nc2qWYDWTfMiXPmPRvhkkz4A0oXTAMDP9xsxUIjYQNsx')
text = (
    'Being open source means anyone can independently review '
    'the code. If it was closed source, nobody could verify the '
    'security. I think it’s essential for a program of this '
    'nature to be open source.'
)
sender = RSASender(public_key)
cipher = sender.encrypt(text)
print(b64encode(cipher))
b'ALwPm7JXWbqGeIflV8PYgprs6mSgCH2Ydy0rgvFolzY0mczKItlPSHueL54uvDJXIz9pXoHZGAOPWVYYbcwRh3EBl8pi3MraUC2BBFUviMPFwNMwza/QMd5DNG9tH8doHlLRRt+15wLrsIE+m5T8fuM4HHixSNcEoOdN8T++q0PkzQDXL+UgbusiD3J+QPO59aqAB5HFcZ7P5U3fhFS8Qm1vLG8vlIulCby0jGLgjTtLUhFD/QhAof0y4F20gxedQDHwAOIrz6PEoBWnHmwLU0QNN0Rs542RvJ8BeEGhBDS5ZvD0/0Ix3ZqKT6HtP4ugfPD75/5LYGioJBwrg2DXbQucFj8='
```

**Comment by VicenteVicente** [comment]
Hola!, los primeros 4 bytes de `public_key` no contienen el largo de `e` (vale 0). No estoy seguro, tal vez entendí mal el formato PEM... 🤔

**Comment by mugartec** [comment]
Whops, usé 8 bytes. Lo arreglo altiro...

**Comment by IchottMano** [comment]
Hola @mugartec !

Para el nuevo ejemplo me aparecen que los primeros 4 bytes de la llave publica son b'\x00\x00\x01\xff', lo cual es igual a 511 bytes, pero el largo de la llave es solo 137 bytes, por lo que no alcanzo a tener valores para N.

Esta correcta la nueva llave publica?

**Comment by IchottMano** [comment]
@mugartec el problema parece ser que segun el enunciado, el primer y tercer numero son la cantidad de **bytes** de e y N, pero en esta llave son la cantidad de **bits** de los numeros, por eso no me esta dando correcto

**Comment by mugartec** [comment]
Efectivamente estaba en bits y en vez de bytes. Ahí lo modifiqué @IchottMano me cuentas si funciona por favor. Gracias!

**Comment by IchottMano** [comment]
Me funciona perfect!

Muchas gracias!

**Comment by Taeval** [comment]
❤️ por el test!
