### ISSUE TITLE
[T2P1] diferencia entre bytes y bytearray

### ISSUE THREAD

**Issue by Aloncarrasco** [UC-IIC3253/2022#55]
Hola, por lo que vi en la tarea nos dice que la función hash generada transforma `bytearrays` en `bytearrays`, sin embargo en el ejemplo que nos dan transforma un objeto `bytes`  `b'Este es un mensaje...'`. 

1) debo esperar que la entrada sea de typo bytearray? que en ese caso sería `bytearray(b'Este es un mensaje...')`. pasa lo mismo con el primer argumento de merkle_damgard. recibe bytes y no un bytearray.

![image](https://user-images.githubusercontent.com/62113089/172211001-19a3975b-d4e9-4e51-abfa-7c286ca25865.png)

adjunto evidencia de lo que digo:
![image](https://user-images.githubusercontent.com/62113089/172217366-2e38b8f3-dac2-40fb-8352-4e0e496bcd58.png)

2) misma pregunta con los retornos de las funciones, ¿deben retornar bytes o bytearrays?

**Comment by marceloarenassaavedra** [comment]
Hola!

Las funciones en esta pregunta deben recibir como parámetros `bytearray` y deben retornar `bytearray`. El enunciado de la tarea fue cambiado dada la confusión entre `bytes` y `bytearray`. El el issue #50 puedes ver ejemplos para probar tu tarea donde todo funciona con `bytearray`.

Saludos!
