### ISSUE TITLE
[T2P2] Ocupar funciones de internet

### ISSUE THREAD

**Issue by Brocoleta** [UC-IIC3253/2022#56]
Hola, para la pregunta 2 puedo ocupar codigos de internet para por ejemplo generar numeros primos o calcular MCD?

**Comment by marceloarenassaavedra** [comment]
No hay problema con que usen código sacado de otras partes siempre que se preocupen de entenderlo, ya que eso va a ser importante para aprobar el examen final.

Saludos!
