### ISSUE TITLE
[T2P2] Función decrypt

### ISSUE THREAD

**Issue by andresplass** [UC-IIC3253/2022#57]
Hola tengo una duda con Decrypt. Entiendo a partir de las clases que tengo que usar el mismo método de Encrypt del enunciado pero cambiando valores de la potencia y debería salir. Estoy medio confundido en esta parte, el texto debería dividirse en bloques de mismo tamaño que en encrypt? y luego de esta secuencia hacer b64decode (u otro decode)?

Como pregunta aparte, los return de key y textos, deben ya estar con b64decode() y b64encode() o éstos se aplicarán como en el test, es decir, después de retornar.

Gracias de antemano :D

**Comment by mugartec** [comment]
Hola @andresplass,

Para encriptar, el mensaje se divide en bloques de `n` bytes donde `n` vale `(N.bit_length() - 1) // 8`. Sin embargo, un bloque encriptado puede usar `n+1` bytes, por lo que el mensaje encriptado será necesariamente más largo que el mensaje original. En la tarea no tienen que hacer nada con base 64, sólo usamos base64 para enviar mensajes que sean más legibles por aquí.
