### ISSUE TITLE
[T2P2] Limpiar output al usar .decode("utf-8")

### ISSUE THREAD

**Issue by fguinez** [UC-IIC3253/2022#58]
Tengo el siguiente código de prueba:
```python
receiver = RSAReceiver(bit_len=512)
sender   = RSASender(receiver.public_key)

text = 'Being'
cipher = sender.encrypt(text)
result = receiver.decrypt(cipher)

print('1', text)
print('2', result)
print('3', result == text)
print('4', len(text))
print('5', len(result))
print('6', result.split())
```
Con el cual obtengo el siguiente output:
```
1 Being
2 Being
3 False
4 5
5 64
6 ['\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Being']
```

Los outputs 1 y 2 parecen indicar que la decriptación es idéntica al mensaje original, sin embargo realmente el largo de la decriptación es mayor (para coincidir con el tamaño de los bloques) y está rellenado con bits vacíos.

Noté que haciendo `result.strip('\x00')` esta situación se soluciona y la decriptación queda idéntica al mensaje original, ¿es necesario manejar estas diferencias entre los 2 strings?

Y de ser así, ¿es una solución válida realizar este strip justo antes de retornar en el método `receiver.decrypt` o debo manejar la situación de tal forma que desde un inicio el bytearray no tenga relleno?

**Comment by mugartec** [comment]
Hola @fguinez.

Todo lo que mencionas es correcto, nice catch.
Esto se arregla considerando último punto del enunciado en "Detalles de implementación":

> Supondremos que el byte 0 nunca vendr´a codificado en el string de entrada, lo que resulta
´util para decriptar el ´ultimo bloque.

Por lo anterior, efectivamente es válido realizar el strip justo antes de retornar en `decrypt`.

**Comment by fguinez** [comment]
Gracias!

Acabo de notar que estaba viendo una versión pasada del enunciado que aún no incluía esa aclaración 😅
