### ISSUE TITLE
Fecha Examen

### ISSUE THREAD

**Issue by Brocoleta** [UC-IIC3253/2022#6]
Hola, nececito saber cuando es la fecha del examen, o bien si es posible de todas las evaluaciones que no las pille en el programa, gracias!

**Comment by marceloarenassaavedra** [comment]
La fecha del examen es el 4 de julio, desde las 8:30am hasta las 12:50pm (módulos 1, 2 y 3).

Agregamos esta información al programa.

Saludos!

**Comment by Brocoleta** [comment]
Gracias!
