### ISSUE TITLE
[T2P1] MerkleDamgard: relación l_block e IV

### ISSUE THREAD

**Issue by StroveLight** [UC-IIC3253/2022#61]
Hola, puedo asumir que ```l_block := len(IV)```?

**Comment by marceloarenassaavedra** [comment]
Sí, puedes suponer esto.

Saludos!

**Comment by marceloarenassaavedra** [comment]
Me equivoque en esta respuesta, no puedes suponer que `l_block = len(IV)`. Lo que sabes es que en la construcción de Merkle–Damgard, la función de compresión va a recibir como parámetro `m_i || H_{i-1}`. El primer parámetro `m_i`es un bloque del mensaje original de largo `l_block`, y el segundo parámetro `H_{i-1}` tiene el mismo largo del vector de inicialización `H_0 = IV` (vale decir `len(IV)`), que además determina el largo del hash que se va a calcular. De esta forma, si la función `encrypt` (en la cual está basada la función de compresión) permite largos distintos para llaves y mensajes, entonces no podemos asumir que `l_block = len(IV)` (en muchos casos estos dos valores son iguales, pero en el caso general no lo son). Perdón por la confusión en esta respuesta.

Saludos
