### ISSUE TITLE
[T2P2] definición bit_len

### ISSUE THREAD

**Issue by StroveLight** [UC-IIC3253/2022#62]
En el enunciado se define bit_len como "A lower bound for the number of bits of N", pero no se menciona cómo se llega al lower_bound, si es con el número en sí o usandolo de exponente de algún otro número. En vista de https://github.com/UC-IIC3253/2022/issues/53#issuecomment-1145991619 parece ser que se usa como exponente de base 2 tal que se use como ```2^bit_len```.  Pero de todas formas lo deseo confirmar

**Comment by mugartec** [comment]
Hola @StroveLight,

El hecho de que `bit_len` sea una cota inferior significa que `N`, al ser representado en binario, debe requerir al menos `bit_len` bits. Por ejemplo, si `bit_len` es 10, `N` debe ser al menos 512.
