### ISSUE TITLE
[T2P2] Version de python

### ISSUE THREAD

**Issue by Ignaciomendezp** [UC-IIC3253/2022#63]
Hola! Para una sección de mi código en la pregunta 2 me corre bien solo si la versión de pyhton es mayor o igual a 3.8. Lo corri en el google colab que tiene 3.7 y me daba error. Podemos asumir que se usará versión mayor o igual a 3.8 en la corrección?
Muchas gracias!

**Comment by StroveLight** [comment]
creo que el enunciado dice implícitamente que es 3.9 el que se usará
![image](https://user-images.githubusercontent.com/48263952/172717612-d6e0bcb9-03d3-41ed-8812-7f02fa3b9c3d.png)

**Comment by marceloarenassaavedra** [comment]
Las tareas las corregimos en la versión de 3.10 de Python.

Saludos!

**Comment by Ignaciomendezp** [comment]
Me parece que la versión de python 3.10 no es compatible al realizar ```AES.new(key,AES.MODE_ECB)```. Lo probé y me dio error, encontré [aquí](https://stackoverflow.com/questions/70705404/systemerror-py-ssize-t-clean-macro-must-be-defined-for-formats) lo relacionado al problema. Para que lo tengan en consideración. Muchas gracias!

**Comment by marceloarenassaavedra** [comment]
Gracias por el comentario, por supuesto lo vamos a tener en cuenta.

Saludos!
