### ISSUE TITLE
[T2P2] Recursion Limit y tiempo total de ejecucción

### ISSUE THREAD

**Issue by bmurtagh01** [UC-IIC3253/2022#66]
Hola!
Quería saber si se va a agrandar el límite de recursion en python (default 1000) en casos que usemos números grandes. Que hay funciones que me corren bien en jupyter pero exportadas en formato .py me obstruye el límite, con 2000 este problema es solucionado. 

Lo otro es una pregunta un poco obvio, como se dice en #53 ¿tenemos entonces 10s de runtime máximo para la P2?

Muchas gracias

**Comment by mugartec** [comment]
Hola @bmurtagh01 el límite de recursión lo dejaremos como está, no es buena práctica hacer funciones recursivas cuando se pueden hacer iterativas porque la recursión introduce un overhead innecesario.

Para la P2, si con 2048 bits la generación de llaves se demora 20 segundos está bien también. No seremos estrictos en eso pero los ayudantes pueden aplicar un descuento si alguna tarea se demora más de lo razonable (20 segundos es razonable).

**Comment by Drpinto1** [comment]
¡Hola @bmurtagh01!

Sobre el tiempo de la P2 ten ojo igual que, como dicen en la misma issue #53, para el N de 2048 bits necesitas generar P y Q de 1024 (lo comento porque me pasó que estaba generándolos de 2048, lo que se demora mucho más y a ratos se pasaba de 20 segundos, pero con 1024 no está ni cerca)
