### ISSUE TITLE
[T2P2] "n es el mayor múltiplo de 8"

### ISSUE THREAD

**Issue by StroveLight** [UC-IIC3253/2022#68]
hola, haciendo la tarea me salió a la duda que el enunciado dice eso
![image](https://user-images.githubusercontent.com/48263952/173069557-268a250e-7ac1-4346-8f2b-079fedbce8a1.png)
pero el enunciado dice que se encripta en bloques de n+1
![image](https://user-images.githubusercontent.com/48263952/173069775-e2b3be06-6e8b-484a-a459-fa6f5f9ca1ff.png)
pero para que funcione la encriptación, se necesiaría usar bloques de n+8, en vez de n+1, ya que n es múltiplo de 8. 

Será que el enunciado quería decir que "8n es el mayor múltiplo de 8", o que se debería usar "n+8" en la encriptación?

**Comment by marceloarenassaavedra** [comment]
En el enunciado `n` se refiere al número de bytes, por ejemplo si para representar `N` se necesita de `2056` bits, entonces se utilizan bloques de `n = 256` bytes al separar el mensaje, ya que este es el mayor valor tal que `8*n < 2056`. Para el mensaje encriptado se necesita utilizar bloques de `n+1` bytes. En el ejemplo anterior, se debe utilizar bloques de `n+1 = 257` bytes, vale decir,  `2056` bits.

Saludos!

**Comment by mugartec** [comment]
Efectivamente no es necesario que `n` sea un múltiplo de 8. Generalmente se usan, pero no es necesario. Está cambiado en el enunciado.
